### ISSUE TITLE
Error updating from 1.2 to 2.x

### ISSUE THREAD

**Issue by claytonpiccinin** [sebdah/dynamic-dynamodb#270] opened 2015-09-24 13:42 UTC
We got this error on CloudFormation trying to update to 2.x:

error_exit 'Failed to install dynamic-dynamodb package from pip repository'

Trying to run it manually we got this error: 

pip install -U dynamic-dynamodb
Collecting dynamic-dynamodb
/usr/local/lib/python2.6/site-packages/pip-7.1.2-py2.6.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading dynamic-dynamodb-2.0.0.tar.gz (67kB)
    100% |████████████████████████████████| 69kB 2.1MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-5Uw6qu/dynamic-dynamodb/setup.py", line 36, in <module>
        install_requires=return_requires(),
      File "/tmp/pip-build-5Uw6qu/dynamic-dynamodb/setup.py", line 19, in return_requires
        install_requires.append('ordereddict >= 1.1')
    AttributeError: 'tuple' object has no attribute 'append'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5Uw6qu/dynamic-dynamodb

**Comment by sebdah** [comment] 2015-09-29 13:01
I can't reproduce this, is this still an issue with release 2.0.1?

**Comment by sebdah** [comment] 2015-10-02 09:20
This is linked to #273 and will be fixed with version 2.1.1.

**Comment by sebdah** [comment] 2015-10-02 09:30
This is now released in version 2.1.1.

**Closed** 2015-12-26 06:22 UTC
Labels: type: bug, type: duplicate
